name: "Run Tests - Older"

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - php: 8.0
            laravel: "10.*"
            dependency-version: prefer-lowest
          - php: 8.0
            laravel: "10.*"
            dependency-version: prefer-stable

          - php: 8.0
            laravel: "9.*"
            dependency-version: prefer-lowest
          - php: 8.0
            laravel: "9.*"
            dependency-version: prefer-stable

          - php: 8.1
            laravel: "9.*"
            dependency-version: prefer-lowest
          - php: 8.1
            laravel: "9.*"
            dependency-version: prefer-stable

          - php: 8.1
            laravel: "9.*"
            dependency-version: prefer-lowest
          - php: 8.1
            laravel: "9.*"
            dependency-version: prefer-stable

          - php: 7.4
            laravel: "7.*"
            dependency-version: prefer-lowest
          - php: 7.4
            laravel: "7.*"
            dependency-version: prefer-stable

          - php: 7.4
            laravel: "8.*"
            dependency-version: prefer-lowest
          - php: 7.4
            laravel: "8.*"
            dependency-version: prefer-stable

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:*" "symfony/console:>=4.3.4" "mockery/mockery:^1.3.2" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit

